name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: gha-demo1
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container: 
      image: node:22-alpine
        # Ye pura "test" job ek Docker container ke andar chalega jisme Node.js 22 Alpine image use hogi

        # Environment variables set karne hai for this image toh mujhe isko under container ke andar set karna padega
        # Agar mujhe koi aur environment variable set karna hai toh mujhe yahan par karna padega
      # env:
        # PORT: 8080   
    env:
      MONGODB_CLUSTER_ADDRESS: mongdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 8080
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
